

###### LOGIN PARA OBTENER TOKEN #######
POST http://localhost:3000/auth/login
Content-Type:   application/json

{
    "username": "profesor",
    "password": "hash_falso_123"
}


####### PRUEBA CON PELICULAS ########

### consultar todas las peliculas
GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg

### consultar una pelicula por id
GET http://localhost:3000/movies/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg

### crear una pelicula
POST http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg
Content-Type:   application/json

{
    "title": "The Matrix Recargado",
    "director": [2,3],
    "posterUrl": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
    "genre": [1,2]
}


### actualizar una pelicula
PUT http://localhost:3000/movies/1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg
Content-Type:   application/json

{
    "title": "The Matrix Reloaded",
    "director": [4,6]
}

### eliminar una pelicula
DELETE http://localhost:3000/movies/1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg



######## PRUEBA CON DIRECTORES ########

### consultar todos los directores
GET http://localhost:3000/directors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg

### consultar un director por id
GET http://localhost:3000/directors/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg

### crear un director
POST http://localhost:3000/directors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg
Content-Type:   application/json

{
    "full_name": "Guillermo del Toro" 
}

### eliminar un director
DELETE http://localhost:3000/directors/6    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg



######## PRUEBA CON GENEROS ########

### consultar todos los generos
GET http://localhost:3000/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg

### consultar un genero por id
GET http://localhost:3000/genres/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg

### crear un genero
POST http://localhost:3000/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg
Content-Type:   application/json

{
    "name": "Thriller"
}

### eliminar un genero
DELETE http://localhost:3000/genres/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg

### actualizar un genero
PUT http://localhost:3000/genres/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsImlhdCI6MTc3NTcwOTQyNCwiZXhwIjoxNzc1NzQ1NDI0fQ.Ucw3OfkTW4V2nDbun5ZD0TMrAHUXhTnAK5LpVuoCGZg
Content-Type:   application/json

{
    "name": "Mystery"
}